name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Remove some games/plugins
      run: |
        rm -rf applications/plugins/tictactoe_game
        rm -rf applications/plugins/tetris_game
        rm -rf applications/plugins/snake_game
        rm -rf applications/plugins/zombiez
        rm -rf applications/plugins/minesweeper
        rm -rf applications/plugins/game15
        rm -rf applications/plugins/flappy_bird
        rm -rf applications/plugins/doom
        rm -rf applications/plugins/arkanoid
        rm -rf applications/plugins/heap_defence_game
        rm -rf applications/plugins/metronome
    - name: Compile Firmware
      run: |
        chmod +x ./fbt
        ./fbt
    - name: Generate artifact
      uses: actions/upload-artifact@v3
      with:
        name: download ZIP
        path: dist/*/*
